testkey=devTestValue
#logging.level.root=INFO
logging.level.com.example.SpringBoot=INFO
#logging.level.com.example.SpringBoot=WARN
#logging.level.com.example.SpringBoot=DEBUG

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console